### PR TITLE
Emit drain event when the request is ready to receive more data

### PR DESCRIPTION
**Pull request by arnaud-lb**
Currently, `HttpClient\Request` isn't a well-behaved `WritableStreamInterface`: `write()` can return `false` (telling the user to stop writing to it until it emits a `drain` event), but there are cases where it never emits a `drain` event: When calling `write()` before the headers have been sent, `write()` returns false and actually writes the body later. However, it doesn't emit a `drain` event.

This is a problem, for instance, when using pipe():

``` php
$request = $client->request("POST", "http://example.com");
Util::pipe($readableStream, $request);
```

`pipe()` will pause `$readableStream` when `$request->write()` returns `false`, and resume `$readableStream` when `$request` emits a `drain` event. If `$request` never emits a drain event, the pipe operation never finishes.

This PR fixes that by emitting a drain event when the request is ready to receive more `write()` calls.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Hey thank you for your PR, sounds and looks good at first glance. Going to review it and come back to you later :+1:

**Comment by clue** [comment]
Changes LGTM :+1:

**Comment by WyriHaximus** [comment]
@clue thanks!

@arnaud-lb My apologise for the delay, things didn't go as planned and I'll go over this PR and merge and tag it tomorrow when I don't find anything with it :)

**Comment by WyriHaximus** [comment]
Thanks again for the PR, I'll tag it shortly

**Comment by arnaud-lb** [comment]
Thanks @WyriHaximus @clue :)

**Pull request merged**
