### PR TITLE
Add end method to ChunkedStreamDecoder for compatibility with Response

### LINKED ISSUE #61: Call to undefined method React\HttpClient\ChunkedStreamDecoder::end()
Hello,

I encountered the following error using the react http client (v0.4.11) : 

```
Call to undefined method React\HttpClient\ChunkedStreamDecoder::end()
```

Indeed in Response.php it seem that ```$this->stream->end()```is not (always?) resolved

Fixed my issue by getting back to 0.4.10.

Cheers.

### PR DESCRIPTION
**Pull request by WyriHaximus**
Fixes #61

### CODE REVIEW

**Comment by clue** [comment]
:-1: This class implements the `ReadableStreamInterface`, while the `end()` method is only defined on the `WritableStreamInterface`. I'm aware of #61, but why is this method called in the first place?

**Comment by WyriHaximus** [comment]
`end()` is called because the stream coming into `Response` is a `DuplexStreamInterface` and `close()` kills off the response with an exception.

Another option to this issue is to check if `$this->stream` implements `WritableStreamInterface` before calling `end()`.

**Comment by clue** [comment]
I've just checked the `Response` class, afaict it actually violates the stream interface by calling `end()` within its `close()` method, so I think this should be fixed.

Also, afaict it doesn't really make sense this expects a `DuplexStreamInterface` in the first place, as it's only using its read-only side anyway. We should be able to change this to a `ReadableStreamInterface` without causing a BC break (Liskov substitution principle).

I'd vote for closing this one to keep this discussion and vote for somebody to file a new PR that fixes this in the `Response` instead :+1:

**Comment by WyriHaximus** [comment]
That makes even more sense, I'll close this PR and file a new PR shortly with the suggested change :+1: .

**Pull request closed without merging**
