### PR TITLE
Avoid hidding exceptions thrown in HttpClient\Request error handlers

### PR DESCRIPTION
**Pull request by arnaud-lb**
`then()` catches exceptions, which is not desirable when its result is not returned.

The following code throws an exception in the 'error' event handler. However, the exception is caught because the event is fired in a `then()` callback.

This PR fixes this by changing a `then` to a `done`.

``` php
$requestData = new RequestData('GET', 'http://www.example.com');
$request = new Request($this->connector, $requestData);

$request->on('error', function () {
    throw new \Exception();
});

$request->end();
```

Actual use case:

``` php
$requestData = new RequestData('GET', 'http://www.example.com');
$request = new Request($this->connector, $requestData);

$deferred = new Deferred();

$request->on('error', function ($err) use ($deferred) {
    $deferred->reject($err);
});

$deferred->done(); // Throws an exception if the deferred is rejected.
                   // Without the PR, the exception is caught.

$request->end();
```

### CODE REVIEW

**Comment by clue** [comment]
Thanks for spotting! These could certainly introduce some subtle and hard to trace issues.

Afaict you're trying to  throw` an `Exception` in the `data` (or `error`) event handler? I'm not quite sure this has been tested extensively. Also, I'm not quite sure *how* this should be handled ideally.

Can you provide a simple gist that exhibits this?

**Comment by arnaud-lb** [comment]
Hi @clue,

> Afaict you're trying to throwanExceptionin thedata(orerror`) event handler? I'm not quite sure this has been tested extensively. Also, I'm not quite sure how this should be handled ideally.

I guess the request/response shouldn't be considered to be in a consistent state after that :)

But at least, the exception should be allowed to unwind and eventually trigger a visible error if not caught by user code.

> I'm not quite sure this has been tested extensively

I'm guilty, I didn't planned for that when I wrote reactphp/http-client :)

> Can you provide a simple gist that exhibits this?

Sure ! Here it is: https://gist.github.com/arnaud-lb/71cf44ab2564b810b463

As you can see, I'm not throwing an exception myself. (And at first, one wouldn't think that the exception is thrown in the error event handler; but it is.)

However, I'm expecting to at least see exceptions that are thrown.

The problem disappears after merging both https://github.com/reactphp/dns/pull/26 and reactphp/http-client#31.

Thanks!

**Comment by WyriHaximus** [comment]
Going to review and test this tonight and get back to it here, thanks for spotting :+1:

**Comment by WyriHaximus** [comment]
LGTM :+1: , @clue do you want to check, merge and tag reactphp/dns#26 first before signing this one off or should I go ahead and merge and tag this one first?

**Comment by clue** [comment]
Thanks for the background @arnaud-lb!

LGTM :+1: 

@WyriHaximus both PRs LGTM, so feel free to review the other one and push either one forward :+1:

**Comment by clue** [comment]
Ping @arnaud-lb, can you update this to require `react/promise: ~2.2`?

Otherwise LGTM :+1:

**Comment by jsor** [comment]
LGTM :+1:

**Pull request merged**
