### PR TITLE
Store response data as property of Response object

### PR DESCRIPTION
**Pull request by Renegade334**
Currently, after the creation of the response object, the only way to access data received from the stream is to construct a buffer and feed into it data received from the response object's `'data'` events. This is cumbersome, and the vast vast majority of uses for the client will only necessitate receiving the contents of the response in full once the request has been fully served.

To that end, this changeset stores the data buffer as a property of the `Response` object, accessible with a getter function as per other response attributes. With this functionality, accessing the HTTP response content is transformed from the complicated process of setting callback handlers to process the creation of the response object and receiving chunked data, to something akin to the following:

``` php
$request = $client->request('GET', 'https://github.com/reactphp/http-client/');
$request->on('end', function ($error, $response) {
    // error handling...

    $data = $response->getContent();
    // process the data
});
$request->end();
```

I will leave this here for more experienced eyes to consider. Feel free to cherry-pick or modify.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Love the feature and this will work fine with small files. But when dealing with a ton of files or dealing with a bunch of very big files all their contents get loaded into the memory and there is a good change you run of memory within the limit or actual RAM. (Mileage may vary depending on hardware and configuration.)

**Comment by Renegade334** [comment]
Aye. Could be made toggleable, either with an additional `Client::request()` parameter, or with an option setter along the lines of `Response::setSaveResponseContent()` which could then be called by a `'response'` event listener.

**Comment by hiend** [comment]
```php
$request->once('response', function (Response $response) {
    \React\Stream\BufferedSink::createPromise($response)->then(function ($content) {
        echo $content;
    });
});
```

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and it's unlikely this will get traction any time soon. The stream semantics have been fixed in recent updates, so buffering the request body is now significantly easier.

The feature request is still open in #48 and we'll look into this in the not too far future :+1: This will also be relevant once we implement PSR-7 interfaces via #41. If you feel this was closed prematurely or want to pick this up again, please let us know and we can reopen this.

Thank you for your effort!

**Pull request closed without merging**
