### PR TITLE
Update SocketClient to v0.6

### PR DESCRIPTION
**Pull request by clue**

### CODE REVIEW

**Comment by jsor** [comment]
I've filed #75 to fix the tests.

**Comment by WyriHaximus** [comment]
@jsor merged #75, could you rebase? :shipit:

**Comment by jsor** [comment]
@WyriHaximus This is @clue's PR ;)

**Comment by clue** [comment]
Rebased on current master now that #75 is in :shipit:

**Comment by WyriHaximus** [comment]
LGTM, but do we want to release this in `v0.4.17` or make a larger release `v0.5.0` with breaking changes?

**Comment by clue** [comment]
Afaict while this does limit which what dependency versions this is compatible, it does not cause a BC break. I know we've had this discussion before, so I'll leave this up to you :+1: 

I'm currently looking into providing proper streaming support for v0.5.0, so we may as well delay this.

**Comment by WyriHaximus** [comment]
> I'm currently looking into providing proper streaming support for v0.5.0, so we may as well delay this

Sounds like a good plan to me 👍

**Pull request merged**
