### PR TITLE
Add basic proxy support

### PR DESCRIPTION
**Pull request by arnaud-lb**
This adds basic proxy support to the HTTP client:

``` php
<?php
$proxyConfig = new ProxyConfig("127.0.0.1", 3128);
$request = $client->request("GET", "http://example.com/", [], '1.0', $proxyConfig);
```

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Looking good :+1: ! Going to try this out in the wild before merging

**Comment by arnaud-lb** [comment]
Ping ? :)

**Comment by WyriHaximus** [comment]
Yes sorry it's high on my to do list. Set up a proxy at home a while back, will try and test it out tonight :)

**Comment by clue** [comment]
I'd love to see this feature in, however I'm seeing several issues with the current approach:

* The `ProxyConfig` has to be passed to every call, which means that higher level abstractions need to know about the proxy concept (leaky abstraction).
* Not sure how useful a `ProxyConfig` class actually is if it's mere purpose is holding two members.
* The `ProxyConfig` currently takes an IP and port, IMO a URI makes more sense.
* The implementation does (only) support proxying plain HTTP requests through a plain HTTP proxy
* The implementation does not support proxying secure HTTPS requests through a plain HTTP proxy (HTTP CONNECT), this will potentially break higher level abstractions.
* The implementation does not support proxying any requests through a secure HTTPS proxy (which I'm okay with as it can be considered a separate feature)

FWIW (not sure how useful this is), but have you checked out https://github.com/clue/php-buzz-react/issues/7 @arnaud-lb ?

**Comment by clue** [comment]
As much as I'd love to get this feature in, I'm having to close this for now as it hasn't received any input in a while and it's unlikely this will get traction any time soon.

The feature request is still open in #44 and we'll look into this in the not too far future :+1: If you feel this was closed prematurely or want to pick this up again, please let us know and we can reopen this.

Thank you for your effort!

**Pull request closed without merging**
