### PR TITLE
Add PHP 7.1 in Travis tests

### PR DESCRIPTION
**Pull request by Th3Mouk**
Add PHP 7.1 since it was released and nightly will be PHP 7.2

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Good catch, thanks :+1:

**Comment by clue** [comment]
Not a big fan of this TBH. I think it makes sense to (eventually) decide which versions it's worth checking against :+1:

**Comment by WyriHaximus** [comment]
Agreed, but testing against 7.1 and 7.2 on other projects already revealed small bugs due to small fixes between 7.0, 7.1, & 7.2.

**Comment by Th3Mouk** [comment]
If I had it like that, it's because tests already passing. If not we can allow_failure but with new regular release of PHP version, its important to test each version. PHP devs move faster than before.

**Pull request merged**
