### PR TITLE
Fix chunk header to be case-insensitive and allow leading zeros for end chunk

### PR DESCRIPTION
**Pull request by mdrost**

### CODE REVIEW

**Comment by clue** [comment]
@mdrost Thanks for filing this PR! It looks like your PR fixes a real bug (uppercase chunk header), but it also changes quite a bit of code that appears to be unrelated to this, so I wonder if you can give us some background here or update this to only change related code. Thanks!

**Comment by clue** [comment]
Also ping @legionth, is this also relevant for react/http?

**Comment by mdrost** [comment]
After fixing uppercase chunk header Wizzair site from https://github.com/reactphp/http-client/issues/76 still throws exception. Wizzair terminating chunk contains 8 zeros but ChunkedStreamDecoder only looks for 1 zero.

**Comment by WyriHaximus** [comment]
> Also ping @legionth, is this also relevant for react/http?

I think it is, will file a PR later today 👍 .

**Comment by legionth** [comment]
@clue @WyriHaximus I'm currently not on my development system. I think this line: https://github.com/reactphp/http/blob/master/src/ChunkedDecoder.php#L103
Should take care of this.
At least there are missing tests in react/http for this.

**Comment by mdrost** [comment]
Shouldn't it be better to have only one chunked decoder? :face_with_head_bandage:

**Comment by WyriHaximus** [comment]
@mdrost We have plans for that

**Comment by WyriHaximus** [comment]
@mdrost for reference #78

**Pull request merged**
