### PR TITLE
chore(docs): remove leading dollar sign

### PR DESCRIPTION
**Pull request by nhedger**
See https://github.com/reactphp/http/pull/458

### CODE REVIEW

**Review by clue — COMMENTED** [review]
@nhedger Changes LGTM, but I'm not sure how much sense it makes to update the legacy HttpClient component. This component has been deprecated as per #152 circa 2 years ago.

**Comment by nhedger** [comment]
Made sense to me because the first code block gives instructions to install the new `reactphp/http` component but I guess it's not absolutely necessary.

**Review by WyriHaximus — APPROVED** [review]
We can still remove it here to be honest. It won't hurt anyone :).

**Comment by clue** [comment]
I don't have any strong opinions on this one and I'm still not sure what to do about this PR, but I'm currently leaning towards not maintaining this component anymore as per #152/#153.

GitHub prominently features the date the project and individual files have been last updated, so I feel merging this PR might come over as this project being "resurrected". I'd rather convey the fact that this project is in fact "dead" prominently.

It's my understanding that if we accept this PR, there's reason to believe we should do more housekeeping for this project, like updating the failing test suite and more. Even if we don't do this ourselves, there's a chance somebody else might look into this and reasonably ask for a PR review. Personally, I'd rather spend time on working the current HTTP component instead.

**Comment by nhedger** [comment]
I agree. Wouldn't it make sense to archive the repository in that case ?

**Pull request closed without merging**
