### PR TITLE
Ensure Request emits initial Response data as string

### PR DESCRIPTION
**Pull request by mmelvin0**
Addresses issue #65.

### CODE REVIEW

**Comment by clue** [comment]
Thanks! Functionally, the changes LGTM :+1: However, semantically, does it make more sense to already cast this in the `parseResponse()` method?

**Comment by WyriHaximus** [comment]
@clue that makes sense to me, @mmelvin0 can you change that? I'll merge and tag right after :+1:

**Comment by WyriHaximus** [comment]
Awesome thanks :+1:

**Comment by WyriHaximus** [comment]
FYI: https://github.com/reactphp/http-client/releases/tag/v0.4.13

**Pull request merged**
