### PR TITLE
Basic "100 Continue" support

### PR DESCRIPTION
**Pull request by nick4fake**
#94

### CODE REVIEW

**Comment by nick4fake** [comment]
@clue 

> Also, the response is actually a "complete" response, which means that we actually have to buffer this to deal with response headers etc. See also #94 for more details.

Actually, I have copied working code from the project :)
There is a return that skips further processing

**Comment by clue** [comment]
Perhaps an example may help, but the following is actually a valid intermediary `100` (Continue) response:

```
HTTP/1.1 100 Go On!\r\n
Server: ReactPHP\r\n
X-Powered-By:PHP 3\r\n
\r\n
HTTP/1.1 200 Yey!\r\n
Content-Length: 2\r\n
\r\n
OK
```

**Comment by nick4fake** [comment]
@clue yep, you are right. I should have read RFC more accurately

**Comment by clue** [comment]
@nick4fake Thank you for looking into this and confirming this!

I believe this has been answered, so I'm closing this for now. Please come back with more details if this persists and we can reopen this :+1:

**Pull request closed without merging**
